org: paky88
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
# Impostazione permessi delle funzioni
  iam:
      role:
        statements:
          - Effect: 'Allow'
            Action:
              - 'dynamodb:PutItem'
              - 'dynamodb:Get*'
              - 'dynamodb:Scan*'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DeleteItem'
            Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-customerTable-${sls:stage}
# Rendere disponibile il nome della tabella            
  environment:
    DYNAMODB_CUSTOMER_TABLE: ${self:service}-customerTable-${sls:stage}
# Aggiunta endpoint
functions:
# Nome funzione specifica
  createCustomer:
# Dove risiede il codice della funzione
    handler: createCustomer.createCustomer
    events:
      - httpApi:
          path: /
          method: post
# Aggiunta edpoint GET          
  getCustomers:
    handler: getCustomers.getCustomers
    events:
      - httpApi:
          path: /customers
          method: get
# database dynamo DB
resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: primary_key
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: primary_key
            KeyType: HASH
        TableName: ${self:service}-customerTable-${sls:stage}

# Aggiunta endpoint POST
function:
createCustomer:
  handler: createCustomer.createCustomer
  events:
    - httpApi:
        path: /
        method: post

    